; NSIS Installer Script for Spanish Conjugation Practice
; Modern installer with comprehensive features

!define APP_NAME "Spanish Conjugation Practice"
!define APP_EXECUTABLE "SpanishConjugation.exe"
!define APP_VERSION "2.0.0"
!define APP_PUBLISHER "Spanish Learning Tools"
!define APP_DESCRIPTION "Spanish Conjugation Practice with AI-powered feedback"
!define APP_HOMEPAGE "https://github.com/yourusername/conjugation_gui"
!define APP_REGISTRY_KEY "Software\SpanishConjugationPractice"
!define UNINSTALL_REGISTRY_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\SpanishConjugationPractice"

; Installer settings
Name "${APP_NAME}"
OutFile "SpanishConjugationSetup_v${APP_VERSION}.exe"
InstallDir "$PROGRAMFILES64\${APP_NAME}"
InstallDirRegKey HKLM "${APP_REGISTRY_KEY}" "InstallDir"
RequestExecutionLevel admin
SetCompressor /SOLID lzma
ShowInstDetails show
ShowUnInstDetails show

; Modern UI
!include "MUI2.nsh"
!include "nsDialogs.nsh"
!include "LogicLib.nsh"
!include "FileFunc.nsh"
!include "WinVer.nsh"

; Modern UI Configuration
!define MUI_ICON "assets\icon.ico"
!define MUI_UNICON "assets\icon.ico"
!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_RIGHT
!define MUI_HEADERIMAGE_BITMAP "assets\header.bmp"
!define MUI_WELCOMEFINISHPAGE_BITMAP "assets\wizard.bmp"
!define MUI_ABORTWARNING

; Installer pages
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "LICENSE"
!insertmacro MUI_PAGE_COMPONENTS
Page custom APIKeyPageCreate APIKeyPageLeave
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_WELCOME
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH

; Languages
!insertmacro MUI_LANGUAGE "English"

; Version Information
VIProductVersion "${APP_VERSION}.0"
VIAddVersionKey "ProductName" "${APP_NAME}"
VIAddVersionKey "ProductVersion" "${APP_VERSION}"
VIAddVersionKey "FileDescription" "${APP_DESCRIPTION}"
VIAddVersionKey "FileVersion" "${APP_VERSION}"
VIAddVersionKey "CompanyName" "${APP_PUBLISHER}"
VIAddVersionKey "LegalCopyright" "Copyright 2024 ${APP_PUBLISHER}"

; Variables
Var APIKeyDialog
Var APIKeyText
Var APIKeyLabel
Var APIKeyValue

; Custom API Key configuration page
Function APIKeyPageCreate
    nsDialogs::Create 1018
    Pop $APIKeyDialog

    ${If} $APIKeyDialog == error
        Abort
    ${EndIf}

    ${NSD_CreateLabel} 0 0 100% 30u "Please enter your OpenAI API Key. You can get one from https://platform.openai.com/api-keys"
    Pop $APIKeyLabel

    ${NSD_CreateText} 0 35u 100% 12u ""
    Pop $APIKeyText
    
    ${NSD_CreateLabel} 0 52u 100% 20u "Note: Your API key will be stored securely in the application's .env file. You can change it later if needed."

    nsDialogs::Show
FunctionEnd

Function APIKeyPageLeave
    ${NSD_GetText} $APIKeyText $APIKeyValue
    ${If} $APIKeyValue == ""
        MessageBox MB_ICONEXCLAMATION|MB_OK "Please enter your OpenAI API key to continue."
        Abort
    ${EndIf}
FunctionEnd

; Installation sections
Section "Core Application" SecCore
    SectionIn RO ; Read-only section
    
    ; Set output path
    SetOutPath "$INSTDIR"
    
    ; Install main executable
    File "dist\${APP_EXECUTABLE}"
    
    ; Install support files
    File ".env.example"
    File /nonfatal "README.md"
    File /nonfatal "LICENSE"
    
    ; Create .env file with API key
    FileOpen $0 "$INSTDIR\.env" w
    FileWrite $0 "OPENAI_API_KEY=$APIKeyValue$\r$\n"
    FileWrite $0 "# Spanish Conjugation Practice Configuration$\r$\n"
    FileWrite $0 "# Generated by installer on $$(date)$\r$\n"
    FileClose $0
    
    ; Set file permissions for .env (restrict access)
    AccessControl::SetFileOwner "$INSTDIR\.env" "$USERNAME"
    AccessControl::SetOnFile "$INSTDIR\.env" "$USERNAME" "FullAccess"
    AccessControl::SetOnFile "$INSTDIR\.env" "Everyone" "NoAccess"
    
    ; Create uninstaller
    WriteUninstaller "$INSTDIR\Uninstall.exe"
    
    ; Write registry keys
    WriteRegStr HKLM "${APP_REGISTRY_KEY}" "InstallDir" "$INSTDIR"
    WriteRegStr HKLM "${APP_REGISTRY_KEY}" "Version" "${APP_VERSION}"
    WriteRegStr HKLM "${APP_REGISTRY_KEY}" "APIKeyConfigured" "Yes"
    
    ; Add uninstall information
    WriteRegStr HKLM "${UNINSTALL_REGISTRY_KEY}" "DisplayName" "${APP_NAME}"
    WriteRegStr HKLM "${UNINSTALL_REGISTRY_KEY}" "DisplayVersion" "${APP_VERSION}"
    WriteRegStr HKLM "${UNINSTALL_REGISTRY_KEY}" "Publisher" "${APP_PUBLISHER}"
    WriteRegStr HKLM "${UNINSTALL_REGISTRY_KEY}" "UninstallString" "$INSTDIR\Uninstall.exe"
    WriteRegStr HKLM "${UNINSTALL_REGISTRY_KEY}" "InstallLocation" "$INSTDIR"
    WriteRegStr HKLM "${UNINSTALL_REGISTRY_KEY}" "DisplayIcon" "$INSTDIR\${APP_EXECUTABLE}"
    WriteRegStr HKLM "${UNINSTALL_REGISTRY_KEY}" "URLInfoAbout" "${APP_HOMEPAGE}"
    WriteRegDWORD HKLM "${UNINSTALL_REGISTRY_KEY}" "NoModify" 1
    WriteRegDWORD HKLM "${UNINSTALL_REGISTRY_KEY}" "NoRepair" 1
    
    ; Calculate installed size
    ${GetSize} "$INSTDIR" "/S=0K" $0 $1 $2
    IntFmt $0 "0x%08X" $0
    WriteRegDWORD HKLM "${UNINSTALL_REGISTRY_KEY}" "EstimatedSize" "$0"

SectionEnd

Section "Desktop Shortcut" SecDesktop
    CreateShortcut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\${APP_EXECUTABLE}" "" "$INSTDIR\${APP_EXECUTABLE}" 0
SectionEnd

Section "Start Menu Shortcuts" SecStartMenu
    CreateDirectory "$SMPROGRAMS\${APP_NAME}"
    CreateShortcut "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk" "$INSTDIR\${APP_EXECUTABLE}" "" "$INSTDIR\${APP_EXECUTABLE}" 0
    CreateShortcut "$SMPROGRAMS\${APP_NAME}\Uninstall.lnk" "$INSTDIR\Uninstall.exe" "" "$INSTDIR\Uninstall.exe" 0
SectionEnd

Section "Visual C++ Redistributable" SecVCRedist
    ; Check if VC++ Redistributable is already installed
    ReadRegStr $0 HKLM "SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64" "Installed"
    ${If} $0 != "1"
        ; Download and install VC++ Redistributable
        MessageBox MB_YESNO|MB_ICONQUESTION "The application requires Microsoft Visual C++ Redistributable. Download and install it now?" IDNO skip_vcredist
        
        ; You would include the redistributable or download it
        ExecWait '"$TEMP\vc_redist.x64.exe" /quiet'
        
        skip_vcredist:
    ${EndIf}
SectionEnd

; Component descriptions
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
    !insertmacro MUI_DESCRIPTION_TEXT ${SecCore} "Core application files (required)"
    !insertmacro MUI_DESCRIPTION_TEXT ${SecDesktop} "Create a desktop shortcut"
    !insertmacro MUI_DESCRIPTION_TEXT ${SecStartMenu} "Create Start Menu shortcuts"
    !insertmacro MUI_DESCRIPTION_TEXT ${SecVCRedist} "Install Visual C++ Redistributable if needed"
!insertmacro MUI_FUNCTION_DESCRIPTION_END

; Installation functions
Function .onInit
    ; Check Windows version
    ${IfNot} ${AtLeastWin10}
        MessageBox MB_ICONSTOP "This application requires Windows 10 or later."
        Abort
    ${EndIf}
    
    ; Check for existing installation
    ReadRegStr $0 HKLM "${UNINSTALL_REGISTRY_KEY}" "UninstallString"
    ${If} $0 != ""
        MessageBox MB_YESNO|MB_ICONQUESTION "${APP_NAME} is already installed. Do you want to uninstall the previous version first?" IDNO skip_uninstall
        ExecWait '$0 /S'
        skip_uninstall:
    ${EndIf}
    
    ; Check if running as administrator
    UserInfo::GetAccountType
    pop $0
    ${If} $0 != "admin"
        MessageBox MB_ICONSTOP "Administrator privileges are required to install this application."
        SetErrorLevel 740 ; ERROR_ELEVATION_REQUIRED
        Abort
    ${EndIf}
FunctionEnd

Function .onInstSuccess
    ; Show completion message with instructions
    MessageBox MB_ICONINFORMATION "${APP_NAME} has been installed successfully!$\n$\nYou can now launch the application from the Start Menu or Desktop shortcut."
    
    ; Ask if user wants to launch the application
    MessageBox MB_YESNO|MB_ICONQUESTION "Would you like to launch ${APP_NAME} now?" IDNO skip_launch
    ExecShell "open" "$INSTDIR\${APP_EXECUTABLE}"
    skip_launch:
FunctionEnd

; Uninstaller section
Section "Uninstall"
    ; Remove files
    Delete "$INSTDIR\${APP_EXECUTABLE}"
    Delete "$INSTDIR\.env"
    Delete "$INSTDIR\.env.example"
    Delete "$INSTDIR\README.md"
    Delete "$INSTDIR\LICENSE"
    Delete "$INSTDIR\Uninstall.exe"
    Delete "$INSTDIR\*.log"
    Delete "$INSTDIR\*.db"
    Delete "$INSTDIR\*.txt"
    
    ; Remove directories
    RMDir "$INSTDIR"
    
    ; Remove shortcuts
    Delete "$DESKTOP\${APP_NAME}.lnk"
    Delete "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk"
    Delete "$SMPROGRAMS\${APP_NAME}\Uninstall.lnk"
    RMDir "$SMPROGRAMS\${APP_NAME}"
    
    ; Remove registry keys
    DeleteRegKey HKLM "${UNINSTALL_REGISTRY_KEY}"
    DeleteRegKey HKLM "${APP_REGISTRY_KEY}"
    
    ; Remove from startup if added
    DeleteRegValue HKCU "Software\Microsoft\Windows\CurrentVersion\Run" "${APP_NAME}"
    
SectionEnd

Function un.onInit
    ; Confirm uninstallation
    MessageBox MB_YESNO|MB_ICONQUESTION "Are you sure you want to completely remove ${APP_NAME}?" IDYES continue_uninstall
    Abort
    continue_uninstall:
FunctionEnd

Function un.onUninstSuccess
    MessageBox MB_ICONINFORMATION "${APP_NAME} has been successfully removed from your computer."
FunctionEnd